"""
Schema definitions for IC-MCP tools.

This module provides Pydantic models for input validation and output serialization,
as well as JSON Schema validation utilities.
"""

from ic_mcp.schemas.inputs import (
    AdminPingInput,
    EnvAggregateInput,
    EnvPeekInput,
    EnvSearchInput,
    EnvSliceInput,
    MemoryGetInput,
    MemoryListInput,
    MemoryPackInput,
    MemoryPinInput,
    MemoryStatsInput,
    MemoryUnpinInput,
    ProjectCommandsInput,
    ProjectImpactInput,
    ProjectMapInput,
    ProjectSymbolSearchInput,
    RlmMapReduceInput,
    RlmPlanInput,
)
from ic_mcp.schemas.outputs import (
    EnvAggregateOutput,
    EnvPeekOutput,
    EnvSearchOutput,
    EnvSliceOutput,
    ErrorEnvelope,
    ErrorInfo,
    Evidence,
    MemoryGetOutput,
    MemoryListOutput,
    MemoryPackOutput,
    MemoryPinOutput,
    MemoryStatsOutput,
    MemoryUnpinOutput,
    ProjectCommandsOutput,
    ProjectImpactOutput,
    ProjectMapOutput,
    ProjectSymbolSearchOutput,
    RlmMapReduceOutput,
    RlmPlanOutput,
    SourceInfo,
    Span,
    SuccessEnvelope,
)
from ic_mcp.schemas.validation import (
    TokenBudget,
    truncate_to_token_budget,
    validate_input,
    validate_output,
)

__all__ = [
    # Input models
    "MemoryPackInput",
    "MemoryPinInput",
    "MemoryUnpinInput",
    "MemoryListInput",
    "MemoryGetInput",
    "MemoryStatsInput",
    "EnvSearchInput",
    "EnvPeekInput",
    "EnvSliceInput",
    "EnvAggregateInput",
    "ProjectMapInput",
    "ProjectSymbolSearchInput",
    "ProjectImpactInput",
    "ProjectCommandsInput",
    "RlmPlanInput",
    "RlmMapReduceInput",
    "AdminPingInput",
    # Output models
    "MemoryPackOutput",
    "MemoryPinOutput",
    "MemoryUnpinOutput",
    "MemoryListOutput",
    "MemoryGetOutput",
    "MemoryStatsOutput",
    "EnvSearchOutput",
    "EnvPeekOutput",
    "EnvSliceOutput",
    "EnvAggregateOutput",
    "ProjectMapOutput",
    "ProjectSymbolSearchOutput",
    "ProjectImpactOutput",
    "ProjectCommandsOutput",
    "RlmPlanOutput",
    "RlmMapReduceOutput",
    "ErrorEnvelope",
    "ErrorInfo",
    "Evidence",
    "SourceInfo",
    "Span",
    "SuccessEnvelope",
    # Validation utilities
    "validate_input",
    "validate_output",
    "truncate_to_token_budget",
    "TokenBudget",
]
